"""
Builds a structured draft report from the model's findings.

This is deliberately template-based rather than free-text-generated by an
LLM: every sentence traces directly back to a specific model probability,
so there's no risk of the report stating something the classifier didn't
actually predict. The tradeoff is that the prose is more mechanical than a
human-written report -- that's an intentional, safety-motivated choice for
a draft clinical document, not an oversight.

The disclaimer block is not optional and is not something callers can
suppress -- it is prepended to every report this function returns.
"""
from datetime import datetime, timezone

DISCLAIMER = (
    "AI-GENERATED DRAFT — NOT FOR CLINICAL USE\n"
    "This report was produced automatically by a research classifier and has not been reviewed "
    "by a radiologist or any licensed clinician. It is not a diagnosis, is not validated for "
    "clinical decision-making, and must not be used to guide patient care. This software is not "
    "an FDA-cleared or otherwise regulatory-approved medical device. All findings require "
    "independent physician review and correlation with clinical history before any action is taken."
)

# Short, plain-language context for each pathology label the model can predict.
PATHOLOGY_CONTEXT = {
    "Atelectasis": "partial collapse of lung tissue",
    "Consolidation": "lung tissue filled with fluid/exudate instead of air",
    "Infiltration": "abnormal substance (e.g. fluid, cells) in lung tissue",
    "Pneumothorax": "air in the pleural space causing lung collapse",
    "Edema": "fluid accumulation in the lungs",
    "Emphysema": "damaged, over-expanded air sacs",
    "Fibrosis": "scarring of lung tissue",
    "Effusion": "fluid collection in the pleural space",
    "Pneumonia": "infection/inflammation of lung tissue",
    "Pleural_Thickening": "thickening of the lung's outer lining",
    "Cardiomegaly": "enlarged heart silhouette",
    "Nodule": "small round opacity, <3cm",
    "Mass": "opacity larger than 3cm",
    "Hernia": "displacement of abdominal contents into the chest cavity",
    "Lung Lesion": "localized abnormal tissue in the lung",
    "Fracture": "break in a bony structure (e.g. rib)",
    "Lung Opacity": "region of increased density on the film",
    "Enlarged Cardiomediastinum": "widened cardiac/mediastinal silhouette",
}


def _severity_word(prob: float) -> str:
    if prob >= 0.85:
        return "high confidence"
    if prob >= 0.65:
        return "moderate-to-high confidence"
    return "moderate confidence"


def generate_report(
    positive_findings: dict[str, float],
    borderline_findings: dict[str, float],
    model_version: str,
    patient_ref: str | None = None,
) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [DISCLAIMER, ""]
    lines.append(f"Study reference: {patient_ref or 'unlabeled'}")
    lines.append(f"Generated: {timestamp}")
    lines.append(f"Model: torchxrayvision ({model_version})")
    lines.append("")
    lines.append("FINDINGS")

    if not positive_findings and not borderline_findings:
        lines.append(
            "  No pathology cleared the model's positive-finding threshold. This does not rule "
            "out disease — a normal-appearing classifier output is not equivalent to a normal "
            "clinical study."
        )
    else:
        for pathology, prob in positive_findings.items():
            context = PATHOLOGY_CONTEXT.get(pathology, "")
            context_str = f" ({context})" if context else ""
            lines.append(
                f"  • {pathology}{context_str} — flagged with {_severity_word(prob)} "
                f"(model probability {prob:.0%})."
            )
        for pathology, prob in borderline_findings.items():
            context = PATHOLOGY_CONTEXT.get(pathology, "")
            context_str = f" ({context})" if context else ""
            lines.append(
                f"  • {pathology}{context_str} — borderline signal, below the positive-finding "
                f"threshold (model probability {prob:.0%}). Reviewer attention suggested but not "
                f"flagged as a positive finding."
            )

    lines.append("")
    lines.append("IMPRESSION")
    if positive_findings:
        top = list(positive_findings.items())[:3]
        summary = ", ".join(f"{p} ({v:.0%})" for p, v in top)
        lines.append(f"  Suggestive of: {summary}. Correlate clinically and with prior imaging.")
    elif borderline_findings:
        lines.append("  No high-confidence findings; borderline signals present. Clinical correlation advised.")
    else:
        lines.append("  No abnormalities flagged by the model at the configured thresholds.")

    lines.append("")
    lines.append(DISCLAIMER)

    return "\n".join(lines)
